development:
  adapter: async

test:
  adapter: async

production:
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  adapter: postgresql
  url: postgres://hvinohffqosmrh:03046d121a0d1ec3d52691857ac513bdbad5de8f66e4b543f588082c9c602166@ec2-23-23-153-145.compute-1.amazonaws.com:5432/d8cm6ob4anmvta
  channel_prefix: riding-vintage_production

# define which adapter to use for ActionCable
